apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: solar_assistant
    user: solar
    secureJsonData:
      password: solar123
    isDefault: true
    editable: true